# Generated by Django 2.1.15 on 2020-04-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='please provide your nick name', max_length=50)),
                ('content', models.CharField(help_text='type your opinion', max_length=150, verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_competitor', models.CharField(max_length=100)),
                ('second_competitor', models.CharField(max_length=100)),
                ('firstCount', models.PositiveIntegerField(default=0)),
                ('secondCount', models.PositiveIntegerField(default=0)),
                ('firstRatio', models.PositiveIntegerField(default=0)),
                ('secondRatio', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_manager.PollModel'),
        ),
    ]
